name: Publish Decomp to Artifactory

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true
      - name: Extract tag version
        id: extract_tag
        run: |
          # Fetch all tags and get the latest one
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "VERSION=$LAST_TAG" >> $GITHUB_ENV
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_TOKEN }}
      - name: Set Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.CONTAINER_REGISTRY }}/${{ github.repository }}/decomp
          tags: type=semver,pattern={{version}},value=${{ env.VERSION }}
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}