name: Build & Release

on:
  push:
    paths: [ 'decomp/target/**' ]
    branches: [ "main" ,"GH-457-1"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: version
        uses: graphitehealth/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: main
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_TOKEN }}
      - name: Set Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.CONTAINER_REGISTRY }}/${{ github.repository }}
          tags: type=semver,pattern={{version}},value=${{ steps.version.outputs.tag }}
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}