name: LOINC change automation
on:
  push:
    branches:
      - main
      # - "**"
    paths:
      - 'LOINC/S2_Elements-LOINC_Extension_map_master.csv'
      - '.github/workflows/s2-terminology-loinc.yaml'

jobs:
  update-loinc:
    runs-on: self-hosted
    concurrency:
      group: s2-terminology
      cancel-in-progress: false
    steps:
      - name: Checkout S2 s2-terminology repository
        uses: actions/checkout@v4
        with:
          path: S2-terminology
          ref: main

      - name: Checkout tools repository
        uses: actions/checkout@v4
        with:
          repository: 'S2health/tools'
          path: tools
          ssh-key: ${{ secrets.TOOLS_DEPLOY_PRIVATE_KEY }}

      - name: Checkout S2-models-demo repository
        uses: actions/checkout@v4
        with:
          repository: 'S2health/S2-models-demo'
          path: S2-models-demo
          ssh-key: ${{ secrets.S2_MODELS_DEMO_DEPLOY_PRIVATE_KEY }}
      
      - name: Create PR in S2-models-demo
        uses: S2health/tools/.github/actions/create-pr@feature/github-actions-template
        with:
          branch_name: "BIND/update-loinc-master"
          scripts_list: "extract_master_loinc_bindings"
          target_repo_name: "S2-models-demo"
          git_pat: ${{ secrets.EDONG_GITHUB_PAT }}
          s2_tools_path: ${{ vars.S2_TOOLS_PATH }}
