name: LOINC master file change automation
on:
  push:
    branches:
      - main
      # - "**"
    paths:
      - 'LOINC/S2_Elements-LOINC_Extension_map_master.csv'
      - '.github/workflows/s2-terminology-loinc.yaml'

jobs:
  update-loinc:
    runs-on: self-hosted
    concurrency:
      group: s2-terminology
      cancel-in-progress: false
    steps:
      - name: Checkout S2 s2-terminology repository
        uses: actions/checkout@v4
        with:
          path: S2-terminology
          ref: main

      - name: Checkout tools repository
        uses: actions/checkout@v4
        with:
          repository: 'S2health/tools'
          path: tools
          ssh-key: ${{ secrets.TOOLS_DEPLOY_PRIVATE_KEY }}
      
      - name: Create PR in this repo
        uses: S2health/tools/.github/actions/create-pr@main
        with:
          branch_name: "wf/extract_loinc_injection_file"
          target_repo_name: ${{ github.event.repository.name }}
          git_pat: ${{ secrets.EDONG_GITHUB_PAT }}
          s2_tools_path: ${{ vars.S2_TOOLS_PATH }}
          scripts_list: |
            extract_master_loinc_bindings --source_repo ${{ github.event.repository.name }}
